package main

import (
	"context"
	_ "embed"
	"encoding/json"
	"os"
	"time"

	"github.com/rs/zerolog"
	"github.com/wailsapp/wails/v3/pkg/application"

	"notify-me/internal/autostart"
	"notify-me/internal/config"
	"notify-me/internal/dispatcher"
	"notify-me/internal/server"
	"notify-me/internal/singleton"
	"notify-me/internal/sound"
	"notify-me/internal/storage"
	"notify-me/internal/tray"
	"notify-me/internal/window"
)

// trayIconPNG is the 16x16 RGBA PNG bundled into the binary so the tray icon
// is available without shipping a separate asset file. Generated by build/.
//
//go:embed build/tray-icon.png
var trayIconPNG []byte

// App is the top-level glue between Wails, the HTTP server, the dispatcher,
// SQLite history and the window manager. The methods exposed to the frontend
// (Banner, Resolve, History, GetConfig, SetConfig, Pause, Resume, Paused,
// ShowMain) are bound through application.NewService(app) in main.go.
type App struct {
	cfg    *config.Config
	log    zerolog.Logger
	db     *storage.Storage
	disp   *dispatcher.Dispatcher
	server *server.Server
	win    *window.Manager
	banner string

	ctx     context.Context
	cancel  context.CancelFunc
	cleanup []func()
}

func NewApp(cfg *config.Config, log zerolog.Logger) *App {
	return &App{cfg: cfg, log: log}
}

// QueueBanner stashes a transient message (e.g. "config corrupted, defaults
// loaded") for the frontend to surface on first paint via Banner().
func (a *App) QueueBanner(msg string) { a.banner = msg }

// Banner returns the currently queued banner string, if any.
func (a *App) Banner() string { return a.banner }

// Boot wires up the runtime subsystems on top of the live Wails app handle.
// Called once from main.go after application.New(...) but before Run().
// On unrecoverable startup errors we surface a native dialog and ask Wails to
// quit cleanly rather than crashing.
func (a *App) Boot(w *application.App) {
	a.ctx, a.cancel = context.WithCancel(context.Background())
	a.win = window.NewManager(w, a.cfg)
	a.win.MountMain()

	closer, err := singleton.ListenForActivation(func() {
		a.win.ShowMain()
	})
	if err != nil {
		a.log.Warn().Err(err).Msg("ipc listen failed")
	} else {
		a.cleanup = append(a.cleanup, closer)
	}

	dbPath, err := config.FilePath("notifications.db")
	if err != nil {
		a.log.Error().Err(err).Msg("resolve db path failed")
		showStartupError("notify-me 启动失败 (resolve db path): " + err.Error())
		w.Quit()
		return
	}
	db, err := storage.Open(dbPath)
	if err != nil {
		a.log.Error().Err(err).Msg("storage open failed")
		showStartupError("notify-me 启动失败 (storage): " + err.Error())
		w.Quit()
		return
	}
	a.db = db
	snap := a.cfg.Snapshot()
	go a.db.RunCleanup(a.ctx, time.Hour, snap.History.RetentionDays, snap.History.MaxRecords)

	a.disp = dispatcher.New(dispatcher.Options{
		QueueSize: snap.Server.MaxQueueSize,
		OnActive:  a.onActive,
	})
	go a.disp.Run(a.ctx)

	a.server = server.New(a.cfg, a.disp, a.db, a.log)
	a.server.OnResolve = func() { a.win.ClosePopup() }
	if err := a.server.Start(); err != nil {
		a.log.Error().Err(err).Msg("server start failed")
		showStartupError("notify-me 启动失败 (server): " + err.Error())
		w.Quit()
		return
	}

	// Tray is mounted last so its handlers close over fully-initialised
	// subsystems (dispatcher, window manager, server). OnQuit runs the same
	// teardown as a normal shutdown then asks Wails to exit the run loop.
	tray.Mount(w, trayIconPNG, tray.Handlers{
		OnShow:   a.win.ShowMain,
		OnPause:  a.disp.Pause,
		OnResume: a.disp.Resume,
		OnQuit: func() {
			a.Shutdown()
			w.Quit()
		},
		Paused: a.disp.IsPaused,
	})
}

// onActive is the dispatcher callback fired when a notification becomes the
// foreground one. We optionally play a sound and pop a fresh popup window.
func (a *App) onActive(n *dispatcher.Notification) {
	payload := map[string]any{
		"id":          n.ID,
		"title":       n.Title,
		"message":     n.Message,
		"ok_text":     n.OkText,
		"cancel_text": n.CancelText,
		"mode":        string(n.Mode),
	}
	if a.cfg.Snapshot().Behavior.SoundEnabled {
		go sound.Play()
	}
	a.win.OpenPopup(payload)
}

// ===== Methods exposed to the frontend (via Wails Service binding) =====

// Resolve is invoked by the popup when the user clicks a button or the popup
// times out client-side. The dispatcher.Resolve call wakes the HTTP handler
// that's blocked on this notification's ResultCh.
func (a *App) Resolve(id int64, decision string) {
	if a.disp == nil {
		return
	}
	a.disp.Resolve(id, dispatcher.Result{Decision: decision})
	if a.win != nil {
		a.win.ClosePopup()
	}
}

// HistoryPage is the JSON shape returned to the main window's history view.
type HistoryPage struct {
	Records []storage.Record `json:"records"`
	Total   int              `json:"total"`
}

// History returns paginated history records, optionally filtered by status
// and/or a free-text search on title and message. status="" means "all statuses".
func (a *App) History(status, search string, limit, offset int) (HistoryPage, error) {
	if a.db == nil {
		return HistoryPage{}, nil
	}
	recs, total, err := a.db.List(a.ctx, storage.ListFilter{Status: status, Search: search, Limit: limit, Offset: offset})
	return HistoryPage{Records: recs, Total: total}, err
}

// DeleteRecord removes a single notification record by ID.
func (a *App) DeleteRecord(id int64) error {
	if a.db == nil {
		return nil
	}
	return a.db.Delete(a.ctx, id)
}

// ClearHistory removes all notification records.
func (a *App) ClearHistory() error {
	if a.db == nil {
		return nil
	}
	return a.db.DeleteAll(a.ctx)
}

// GetConfig returns the live config as a pretty-printed JSON string. The
// frontend edits this string directly in the settings page.
func (a *App) GetConfig() string {
	snap := a.cfg.Snapshot()
	raw, _ := json.MarshalIndent(snap, "", "  ")
	return string(raw)
}

// SetConfig parses the supplied JSON, applies it to the live config, persists
// it to disk, and synchronises the OS-level autostart toggle if it changed.
func (a *App) SetConfig(jsonStr string) error {
	var next config.Config
	if err := json.Unmarshal([]byte(jsonStr), &next); err != nil {
		return err
	}
	prev := a.cfg.Snapshot()
	a.cfg.Apply(next)
	if prev.Behavior.Autostart != next.Behavior.Autostart {
		exe, _ := os.Executable()
		if err := autostart.Set(next.Behavior.Autostart, exe); err != nil {
			a.log.Error().Err(err).Msg("autostart toggle failed")
		}
	}
	return a.cfg.Save()
}

// Pause stops accepting new notifications. The dispatcher continues to deliver
// already-queued items.
func (a *App) Pause() {
	if a.disp != nil {
		a.disp.Pause()
	}
}

// Resume re-enables enqueueing after a Pause.
func (a *App) Resume() {
	if a.disp != nil {
		a.disp.Resume()
	}
}

// Paused reports whether the dispatcher is currently rejecting new
// notifications.
func (a *App) Paused() bool {
	if a.disp == nil {
		return false
	}
	return a.disp.IsPaused()
}

// ShowMain reveals the persistent main window (e.g. when the user clicks the
// tray icon). Mounts the window lazily if it hasn't been created yet.
func (a *App) ShowMain() {
	if a.win != nil {
		a.win.ShowMain()
	}
}

// Shutdown unwinds the runtime subsystems in dependency order: server first
// (so no new dispatcher work arrives), then context cancel (which drains the
// dispatcher's in-flight notifications), then SQLite.
func (a *App) Shutdown() {
	if a.server != nil {
		_ = a.server.Stop(context.Background())
	}
	_ = singleton.Release()
	if a.cancel != nil {
		a.cancel()
	}
	if a.db != nil {
		_ = a.db.Close()
	}
	for _, fn := range a.cleanup {
		fn()
	}
}
