package main

import (
	"bytes"
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"os"
	"sync"
	"time"

	"github.com/rs/zerolog"
	"github.com/wailsapp/wails/v3/pkg/application"

	"notify-me/internal/autostart"
	"notify-me/internal/claudeconfig"
	"notify-me/internal/config"
	"notify-me/internal/dispatcher"
	"notify-me/internal/policy"
	"notify-me/internal/server"
	"notify-me/internal/singleton"
	"notify-me/internal/sound"
	"notify-me/internal/storage"
	"notify-me/internal/tray"
	"notify-me/internal/transcript"
	"notify-me/internal/window"
)

// trayIconPNG is the 44x44 RGBA PNG bundled into the binary so the tray icon
// is available without shipping a separate asset file. Generated by build/.
//
//go:embed build/tray-icon.png
var trayIconPNG []byte

// App is the top-level glue between Wails, the HTTP server, the dispatcher,
// SQLite history and the window manager. The methods exposed to the frontend
// (Banner, Resolve, History, GetConfig, SetConfig, Pause, Resume, Paused,
// ShowMain) are bound through application.NewService(app) in main.go.
type App struct {
	cfg    *config.Config
	log    zerolog.Logger
	db     *storage.Storage
	disp   *dispatcher.Dispatcher
	server *server.Server
	policy *policy.Engine
	win    *window.Manager
	tray   *application.SystemTray
	banner string

	alertIcon []byte
	blinkMu   sync.Mutex
	blinkStop chan struct{} // non-nil while blink goroutine is running

	ctx     context.Context
	cancel  context.CancelFunc
	cleanup []func()
}

func NewApp(cfg *config.Config, log zerolog.Logger) *App {
	return &App{cfg: cfg, log: log}
}

// QueueBanner stashes a transient message (e.g. "config corrupted, defaults
// loaded") for the frontend to surface on first paint via Banner().
func (a *App) QueueBanner(msg string) { a.banner = msg }

// Banner returns the currently queued banner string, if any.
func (a *App) Banner() string { return a.banner }

// Boot wires up the runtime subsystems on top of the live Wails app handle.
// Called once from main.go after application.New(...) but before Run().
// On unrecoverable startup errors we surface a native dialog and ask Wails to
// quit cleanly rather than crashing.
func (a *App) Boot(w *application.App) {
	a.ctx, a.cancel = context.WithCancel(context.Background())
	a.alertIcon = makeAlertIcon(trayIconPNG)
	a.win = window.NewManager(w, a.cfg)
	a.win.MountMain()

	dbPath, err := config.FilePath("notifications.db")
	if err != nil {
		a.log.Error().Err(err).Msg("resolve db path failed")
		showStartupError("notify-me 启动失败 (resolve db path): " + err.Error())
		w.Quit()
		return
	}
	db, err := storage.Open(dbPath)
	if err != nil {
		a.log.Error().Err(err).Msg("storage open failed")
		showStartupError("notify-me 启动失败 (storage): " + err.Error())
		w.Quit()
		return
	}
	a.db = db
	snap := a.cfg.Snapshot()
	go a.db.RunCleanup(a.ctx, time.Hour, snap.History.RetentionDays, snap.History.MaxRecords)

	a.policy = policy.NewEngine(&policyStoreAdapter{db: a.db})

	a.disp = dispatcher.New(dispatcher.Options{
		QueueSize: snap.Server.MaxQueueSize,
		OnActive:  a.onActive,
		OnResolve: a.onNotificationResolved,
	})
	go a.disp.Run(a.ctx)

	a.server = server.New(a.cfg, a.disp, a.db, a.policy, a.log)
	a.server.OnResolve = func(id int64) {
		a.win.ClosePopup()
		a.win.CloseDiffWindow(id)
	}
	a.server.OnCancel = func(id int64) {
		a.win.ClosePopup()
	}
	a.server.OnOpenDiff = func(id int64) {
		a.win.OpenDiffWindow(id)
	}
	a.server.OnSessionAuth = func(sessionID, toolName, pattern string) {
		now := time.Now().UnixMilli()
		a.db.InsertPolicyRule(a.ctx, policy.PolicyRule{
			Type:      policy.RuleTypeSession,
			SessionID: sessionID,
			ToolName:  toolName,
			Pattern:   pattern,
			Enabled:   true,
			Source:    policy.SourcePopup,
			CreatedAt: now,
			UpdatedAt: now,
		})
		a.policy.Reload()
	}
	if err := a.server.Start(); err != nil {
		a.log.Error().Err(err).Msg("server start failed")
		showStartupError("notify-me 启动失败 (server): " + err.Error())
		w.Quit()
		return
	}

	// IPC listener must be registered after server is created so that
	// the onHook callback (server.ProcessHookIPC) is not nil.
	closer, err := singleton.ListenForActivation(func() {
		a.win.ShowMain()
	}, a.server.ProcessHookIPC)
	if err != nil {
		a.log.Warn().Err(err).Msg("ipc listen failed")
	} else {
		a.cleanup = append(a.cleanup, closer)
	}

	// Tray is mounted last so its handlers close over fully-initialised
	// subsystems (dispatcher, window manager, server). OnQuit runs the same
	// teardown as a normal shutdown then asks Wails to exit the run loop.
	a.tray = tray.Mount(w, trayIconPNG, tray.Handlers{
		OnShow:   a.win.ShowMain,
		OnPause:  a.disp.Pause,
		OnResume: a.disp.Resume,
		OnQuit: func() {
			a.Shutdown()
			w.Quit()
		},
		Paused: a.disp.IsPaused,
	})
}

// onActive is the dispatcher callback fired when a notification becomes the
// foreground one. We optionally play a sound and pop a fresh popup window.
func (a *App) onActive(n *dispatcher.Notification) {
	if a.cfg.Snapshot().Behavior.BlinkEnabled {
		a.startBlinking()
	}
	payload := map[string]any{
		"id":          n.ID,
		"title":       n.Title,
		"message":     n.Message,
		"ok_text":     n.OkText,
		"cancel_text": n.CancelText,
		"mode":        string(n.Mode),
		"has_diff":    n.HasDiff,
		"hook_event":  n.HookEvent,
	}
	if a.cfg.Snapshot().Behavior.SoundEnabled {
		go sound.Play()
	}
	a.win.OpenPopup(payload)
}

// ===== Methods exposed to the frontend (via Wails Service binding) =====

// Resolve is invoked by the popup when the user clicks a button or the popup
// times out client-side. The dispatcher.Resolve call wakes the HTTP handler
// that's blocked on this notification's ResultCh.
func (a *App) Resolve(id int64, decision string) {
	if a.disp == nil {
		return
	}
	a.disp.Resolve(id, dispatcher.Result{Decision: decision})
	if a.win != nil {
		a.win.ClosePopup()
	}
}

// HistoryPage is the JSON shape returned to the main window's history view.
type HistoryPage struct {
	Records []storage.Record `json:"records"`
	Total   int              `json:"total"`
}

// History returns paginated history records, optionally filtered by status
// and/or a free-text search on title and message. status="" means "all statuses".
func (a *App) History(status, search string, limit, offset int) (HistoryPage, error) {
	if a.db == nil {
		return HistoryPage{}, nil
	}
	recs, total, err := a.db.List(a.ctx, storage.ListFilter{Status: status, Search: search, Limit: limit, Offset: offset})
	return HistoryPage{Records: recs, Total: total}, err
}

// DeleteRecord removes a single notification record by ID.
func (a *App) DeleteRecord(id int64) error {
	if a.db == nil {
		return nil
	}
	return a.db.Delete(a.ctx, id)
}

// ClearHistory removes all notification records.
func (a *App) ClearHistory() error {
	if a.db == nil {
		return nil
	}
	return a.db.DeleteAll(a.ctx)
}

// GetConfig returns the live config as a pretty-printed JSON string. The
// frontend edits this string directly in the settings page.
func (a *App) GetConfig() string {
	snap := a.cfg.Snapshot()
	raw, _ := json.MarshalIndent(snap, "", "  ")
	return string(raw)
}

// SetConfig parses the supplied JSON, applies it to the live config, persists
// it to disk, and synchronises the OS-level autostart toggle if it changed.
func (a *App) SetConfig(jsonStr string) error {
	var next config.Config
	if err := json.Unmarshal([]byte(jsonStr), &next); err != nil {
		return err
	}
	prev := a.cfg.Snapshot()
	a.cfg.Apply(next)
	if prev.Behavior.Autostart != next.Behavior.Autostart {
		exe, _ := os.Executable()
		if err := autostart.Set(next.Behavior.Autostart, exe); err != nil {
			a.log.Error().Err(err).Msg("autostart toggle failed")
		}
	}
	return a.cfg.Save()
}

// Pause stops accepting new notifications. The dispatcher continues to deliver
// already-queued items.
func (a *App) Pause() {
	if a.disp != nil {
		a.disp.Pause()
	}
}

// Resume re-enables enqueueing after a Pause.
func (a *App) Resume() {
	if a.disp != nil {
		a.disp.Resume()
	}
}

// Paused reports whether the dispatcher is currently rejecting new
// notifications.
func (a *App) Paused() bool {
	if a.disp == nil {
		return false
	}
	return a.disp.IsPaused()
}

// ShowMain reveals the persistent main window (e.g. when the user clicks the
// tray icon). Mounts the window lazily if it hasn't been created yet.
func (a *App) ShowMain() {
	if a.win != nil {
		a.win.ShowMain()
	}
}

// ===== Quick toggles & Home tab data =====

// GetQuickToggles returns sound_enabled, blink_enabled and stop_hook_enabled as JSON.
func (a *App) GetQuickToggles() string {
	snap := a.cfg.Snapshot()
	out, _ := json.Marshal(map[string]bool{
		"sound_enabled":    snap.Behavior.SoundEnabled,
		"blink_enabled":    snap.Behavior.BlinkEnabled,
		"stop_hook_enabled": snap.Behavior.StopHookEnabled,
	})
	return string(out)
}

// SetSoundEnabled toggles the sound setting without a full config round-trip.
func (a *App) SetSoundEnabled(enabled bool) error {
	next := a.cfg.Snapshot()
	next.Behavior.SoundEnabled = enabled
	a.cfg.Apply(next)
	return a.cfg.Save()
}

// SetBlinkEnabled toggles the blink effect setting.
func (a *App) SetBlinkEnabled(enabled bool) error {
	next := a.cfg.Snapshot()
	next.Behavior.BlinkEnabled = enabled
	a.cfg.Apply(next)
	if !enabled {
		a.stopBlinking()
	}
	return a.cfg.Save()
}

// SetStopHookEnabled toggles whether Stop/StopFailure hook events are included.
func (a *App) SetStopHookEnabled(enabled bool) error {
	next := a.cfg.Snapshot()
	next.Behavior.StopHookEnabled = enabled
	a.cfg.Apply(next)
	return a.cfg.Save()
}

// GetHookStatus returns the current Claude Code hook configuration status.
func (a *App) GetHookStatus() string {
	status, err := claudeconfig.GetStatus()
	if err != nil {
		b, _ := json.Marshal(map[string]any{"error": err.Error()})
		return string(b)
	}
	b, _ := json.Marshal(status)
	return string(b)
}

// ConfigureHooks writes notify-me hook entries into Claude Code settings.
// Returns an error if Claude Code is not installed.
func (a *App) ConfigureHooks(mode string) error {
	status, err := claudeconfig.GetStatus()
	if err != nil {
		return fmt.Errorf("检测 Claude Code 状态失败: %w", err)
	}
	if !status.Installed {
		return fmt.Errorf("Claude Code 未安装，请先安装 Claude Code CLI")
	}
	snap := a.cfg.Snapshot()
	httpURL := fmt.Sprintf("http://%s:%d%s/claude/hook",
		snap.Server.Host, snap.Server.Port, snap.Server.EndpointPrefix)
	return claudeconfig.Configure(mode, httpURL, snap.Behavior.StopHookEnabled)
}

// RemoveHooks removes notify-me hook entries from Claude Code settings.
func (a *App) RemoveHooks() error {
	return claudeconfig.Remove()
}

// DashboardStats returns aggregated statistics for the home dashboard.
func (a *App) DashboardStats() string {
	if a.db == nil {
		return "{}"
	}
	ctx := a.ctx
	tools, _ := a.db.ToolUsageCount(ctx)
	decisions, _ := a.db.DecisionStats(ctx)
	avgMs, _ := a.db.AvgResponseTime(ctx)
	sessions, _ := a.db.SessionIDs(ctx)
	total, _ := a.db.TotalCount(ctx)
	b, _ := json.Marshal(map[string]any{
		"tool_usage":      tools,
		"decisions":       decisions,
		"avg_response_ms": avgMs,
		"sessions":        sessions,
		"total":           total,
	})
	return string(b)
}

// SessionTimeline returns recent records for a specific session.
func (a *App) SessionTimeline(sessionID string, limit int) string {
	if a.db == nil {
		return "[]"
	}
	if limit <= 0 {
		limit = 50
	}
	recs, err := a.db.RecentBySession(a.ctx, sessionID, limit)
	if err != nil {
		b, _ := json.Marshal(map[string]any{"error": err.Error()})
		return string(b)
	}
	b, _ := json.Marshal(recs)
	return string(b)
}

// TranscriptMessages parses a Claude Code transcript file and returns
// conversation messages for replay.
func (a *App) TranscriptMessages(transcriptPath string) string {
	msgs, err := transcript.Parse(transcriptPath)
	if err != nil {
		b, _ := json.Marshal(map[string]any{"error": err.Error()})
		return string(b)
	}
	b, _ := json.Marshal(msgs)
	return string(b)
}

// ===== Tray icon blink =====

// startBlinking begins alternating the tray icon between the normal and alert
// versions. If already blinking this is a no-op.
func (a *App) startBlinking() {
	a.blinkMu.Lock()
	defer a.blinkMu.Unlock()
	if a.blinkStop != nil {
		return // already blinking
	}
	stop := make(chan struct{})
	a.blinkStop = stop
	go a.blinkLoop(stop)
}

// stopBlinking stops the blink goroutine and restores the normal icon.
func (a *App) stopBlinking() {
	a.blinkMu.Lock()
	stop := a.blinkStop
	a.blinkStop = nil
	a.blinkMu.Unlock()
	if stop != nil {
		close(stop)
	}
	if a.tray != nil {
		a.tray.SetIcon(trayIconPNG)
	}
}

// blinkLoop runs on a background goroutine and pulses the tray icon in a
// heartbeat pattern: two quick flashes then a short pause, repeating until
// the stop channel is closed.
func (a *App) blinkLoop(stop <-chan struct{}) {
	// heartbeat pattern: flash-pause-flash-pause-longer-pause
	pattern := []time.Duration{
		250 * time.Millisecond, // show alert
		250 * time.Millisecond, // show normal
		250 * time.Millisecond, // show alert
		800 * time.Millisecond, // show normal (longer pause)
	}
	for {
		for i, d := range pattern {
			select {
			case <-stop:
				return
			case <-time.After(d):
				if i%2 == 0 {
					a.tray.SetIcon(a.alertIcon)
				} else {
					a.tray.SetIcon(trayIconPNG)
				}
			}
		}
	}
}

// onNotificationResolved is the dispatcher OnResolve callback. It stops the
// blink when all in-flight notifications have been resolved.
func (a *App) onNotificationResolved() {
	select {
	case <-a.ctx.Done():
		return
	default:
	}
	if a.disp.InFlightCount() == 0 {
		a.stopBlinking()
	}
}

// Shutdown unwinds the runtime subsystems in dependency order: server first
// (so no new dispatcher work arrives), then context cancel (which drains the
// dispatcher's in-flight notifications), then SQLite.
func (a *App) Shutdown() {
	a.stopBlinking()
	if a.win != nil {
		a.win.CloseAllDiff()
	}
	if a.server != nil {
		_ = a.server.Stop(context.Background())
	}
	_ = singleton.Release()
	if a.cancel != nil {
		a.cancel()
	}
	if a.db != nil {
		_ = a.db.Close()
	}
	for _, fn := range a.cleanup {
		fn()
	}
}

// ===== Policy rule management (Wails methods) =====

// GetPolicyRules returns all policy rules as a JSON string.
func (a *App) GetPolicyRules() string {
	if a.db == nil {
		return "[]"
	}
	rules, err := a.db.ListPolicyRules(a.ctx)
	if err != nil {
		b, _ := json.Marshal(map[string]any{"error": err.Error()})
		return string(b)
	}
	b, _ := json.Marshal(rules)
	return string(b)
}

// AddPolicyRule inserts a new policy rule and reloads the engine.
func (a *App) AddPolicyRule(jsonStr string) error {
	if a.db == nil {
		return fmt.Errorf("storage not initialized")
	}
	var r policy.PolicyRule
	if err := json.Unmarshal([]byte(jsonStr), &r); err != nil {
		return err
	}
	_, err := a.db.InsertPolicyRule(a.ctx, r)
	if err != nil {
		return err
	}
	a.policy.Reload()
	return nil
}

// UpdatePolicyRule updates an existing policy rule and reloads the engine.
func (a *App) UpdatePolicyRule(jsonStr string) error {
	if a.db == nil {
		return fmt.Errorf("storage not initialized")
	}
	var r policy.PolicyRule
	if err := json.Unmarshal([]byte(jsonStr), &r); err != nil {
		return err
	}
	if err := a.db.UpdatePolicyRule(a.ctx, r); err != nil {
		return err
	}
	a.policy.Reload()
	return nil
}

// DeletePolicyRule deletes a policy rule by ID and reloads the engine.
func (a *App) DeletePolicyRule(id int64) error {
	if a.db == nil {
		return fmt.Errorf("storage not initialized")
	}
	if err := a.db.DeletePolicyRule(a.ctx, id); err != nil {
		return err
	}
	a.policy.Reload()
	return nil
}

// CleanupSessionRules removes session-scoped rules for inactive sessions.
func (a *App) CleanupSessionRules() error {
	if a.db == nil {
		return fmt.Errorf("storage not initialized")
	}
	if err := a.db.CleanupInactiveSessionRules(a.ctx); err != nil {
		return err
	}
	a.policy.Reload()
	return nil
}

// policyStoreAdapter adapts *storage.Storage to the policy.PolicyStore
// interface by wrapping the context-less ListPolicyRules call.
type policyStoreAdapter struct {
	db *storage.Storage
}

func (a *policyStoreAdapter) ListPolicyRules() ([]policy.PolicyRule, error) {
	return a.db.ListPolicyRules(context.Background())
}

// makeAlertIcon generates an "alert" version of the tray icon by tinting the
// background to a vibrant red while keeping the "NM" text white. Falls back to
// the original if decoding fails.
func makeAlertIcon(original []byte) []byte {
	src, err := png.Decode(bytes.NewReader(original))
	if err != nil {
		return original
	}
	b := src.Bounds()
	dst := image.NewRGBA(b)
	draw.Draw(dst, b, src, b.Min, draw.Src)

	// Replace dark blue (#0d2b4e) background with alert red (#E8413C),
	// keep white text unchanged.
	for y := 0; y < b.Dy(); y++ {
		for x := 0; x < b.Dx(); x++ {
			r, g, b_, a := dst.At(x, y).RGBA()
			if a == 0 {
				continue
			}
			// White text (high brightness) stays white.
			if r>>8 > 200 && g>>8 > 200 && b_>>8 > 200 {
				continue
			}
			dst.Set(x, y, color.RGBA{R: 232, G: 65, B: 60, A: uint8(a >> 8)})
		}
	}

	var buf bytes.Buffer
	if err := png.Encode(&buf, dst); err != nil {
		return original
	}
	return buf.Bytes()
}
